# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c6a999aa4a428eb2910f083404f540e482c655d76fd104e746bfed03e5922720c80b89ddafc84a51592d14a6fd3b783a979e39913fe38fb02adb0a0a501907

test:
  secret_key_base: 353b65798bc1c9dea8191b8dbb4729691ed82551d13c846ba309bd3865cb03c660a9d6dc28804be08fcef0652fd50bd45318ac553daab7adb83e8d85dba48d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
